CREATE TABLE owners
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    address    VARCHAR(255),
    city       VARCHAR(255),
    telephone  VARCHAR(255),
    CONSTRAINT pk_owners PRIMARY KEY (id)
);

CREATE TABLE pets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    type_id    BIGINT,
    owner_id   BIGINT,
    birth_date date,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES owners (id);

CREATE TABLE types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_types PRIMARY KEY (id)
);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_TYPE FOREIGN KEY (type_id) REFERENCES types (id);

CREATE TABLE specialties
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_specialties PRIMARY KEY (id)
);

CREATE TABLE vet_specialties
(
    speciality_id BIGINT NOT NULL,
    vet_id        BIGINT NOT NULL,
    CONSTRAINT pk_vet_specialties PRIMARY KEY (speciality_id, vet_id)
);

CREATE TABLE vets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_vets PRIMARY KEY (id)
);

ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vet_on_speciality FOREIGN KEY (speciality_id) REFERENCES specialties (id);

ALTER TABLE vet_specialties
    ADD CONSTRAINT fk_vet_on_vet FOREIGN KEY (vet_id) REFERENCES vets (id);

CREATE TABLE visits
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date,
    description VARCHAR(255),
    pet_id      BIGINT,
    CONSTRAINT pk_visits PRIMARY KEY (id)
);

ALTER TABLE visits
    ADD CONSTRAINT FK_VISITS_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);